### ISSUE TITLE
PS1's GTE instruction set support

### ISSUE THREAD

**Issue by AngheloAlf** [Decompollaborate/rabbitizer#29]
Support for the "Geometry Transformation Engine" (GTE) instruction set, which is exclusive for the PS1 machines.

Proper documentation for how to decode the instructions is required and has not been found yet

**Comment by marijnvdwerf** [comment]
Was talking with Sonic yesterday, and I did find this. You might have already have it, but I figured it would make sense to share here: http://www.raphnet.net/electronique/psx_adaptor/Playstation.txt

**Comment by AngheloAlf** [comment]
I have seen that document before, yes, but unless I'm missing something obvious, it doesn't have any information on how to _decode_ the instructions themselves, only how to use them and what they do (from a development perspective)

**Comment by marijnvdwerf** [comment]
Do we have some as-of-yet unhandled byte sequences? Because Sonic's code did contain some `CTC2` and `COP2` instructions, which I assume this was about

**Comment by AngheloAlf** [comment]
Sonic sent me a few days ago a function which had a `0x4A180001` instruction, which is a Coprocessor 2 instruction, but we don't know much besides that

**Comment by marijnvdwerf** [comment]
That one is documented in the linked txt.

    Name	Cycles	Command	Description	
    RTPS	15	cop2 0x0180001	Perspective transform

**Comment by AngheloAlf** [comment]
But it doesn't provide any type of mnemonic or registers it uses, unless it takes all this parameters:
![image](https://user-images.githubusercontent.com/7416381/235234609-cb4b0b68-f6fa-4281-bf75-a621da6f519e.png)

**Comment by marijnvdwerf** [comment]
The code I saw from sonic wrote stuff to all those registers using `CTC2` opcodes

**Comment by AngheloAlf** [comment]
References:
- https://github.com/FoxdieTeam/psyq_sdk/blob/master/psyq_4.4/INCLUDE/INLINE_S.H
- https://problemkaputt.de/psxspx-gte-opcode-summary.htm
- https://psx-spx.consoledev.net/geometrytransformationenginegte/#gte-opcode-summary
