### ISSUE TITLE
getBranchVramGeneric returns a signed value

### ISSUE THREAD

**Issue by descawed** [Decompollaborate/rabbitizer#48]
Is this intentional? Logically, it seems to me like an address should be unsigned, and both code paths in the function are returning unsigned expressions. However, the signed definition is repeated in several places, so I wanted to make sure I'm not missing something before I submitted a PR.

**Comment by AngheloAlf** [comment]
I think you are right and this function should return an unsigned value instead. I may just have copy-pasted something without giving it a second thought.
Feel free to open a PR to fix it

**Comment by AngheloAlf** [comment]
Thanks a lot!
