### ISSUE TITLE
EE Core `pmfhl` instruction variants not recognized

### ISSUE THREAD

**Issue by ieee802dot11ac** [Decompollaborate/rabbitizer#65]
While using `splat` to assemble some split files, I noticed that it had not properly recognized the variants of the EE Core-exclusive `pmfhl` instructions (that is, `pmfhl.lh, pmfhl.lw, pmfhl.sh, pmfhl.slw,` and `smfhl.uw`). An example of this can be located at [https://github.com/ieee802dot11ac/amp](https://github.com/ieee802dot11ac/amp), where upon attempted build, ninja should fail with several `asm/32EF00.s: Error: unrecognized opcode 'pmfhl $t0'` errors.

**Comment by AngheloAlf** [comment]
I pushed a commit addressing the `pmfhl.fmt` instructions (ef2598d2c7dd8197771b97fb8fcd3b51d63b9d83). Could you please test it works properly to you?

To install the development version of rabbitizer you can follow the following steps:

```bash
python3 -m pip uninstall rabbitizer
python3 -m pip install git+https://github.com/Decompollaborate/rabbitizer.git@develop
```

I couldn't find any reference to `smfhl.uw`, neither on rabbitizer nor the reference PDFs for the R5900 CPU. Is it a typo? Maybe you meant `pmthl.lw` instruction?

**Comment by ieee802dot11ac** [comment]
Works, and I had meant `pmfhl.uw`.
