### ISSUE TITLE
[Frug]: PSP VFPU instructions need brackets on args

### ISSUE THREAD

**Issue by bismurphy** [Decompollaborate/rabbitizer#69]
### Explain the problem.

I'm working on the PSP decompilation for Castlevania: Symphony of the Night. I have found that some of the PSP-specific VFPU instructions (including `vpfxs` and `vpfxt`) take 4 comma-delimited arguments. Rabbitizer outputs syntax like:

`vpfxs      2, 1, 1, -2`

However, when attempting to assemble with binutils, this creates an "Error: invalid operands". This is because the arguments need to be an array with brackets. Going into the generated assembly and adding the brackets fixes it and allows successful assembling.

I suspect that Rabbitizer is not heavily tested on PSP, especially the unusual VFPU special instructions, so I may just be the first user running into this. If Rabbitizer would output `vpfxs      [2, 1, 1, -2]` the issue would be solved. For reference, the byte sequence for this instruction is `96F008DC` (little-endian).

### Reproducer

Right now there's no good way to reproduce - it would require a lot of setup of the SOTN repo, with my tweaks for pulling in the PSP executable, as well as a copy of the game. Given that the only required change is adding brackets to the start and end of the operands string, hopefully this is an easy adjustment to make.

### Is this issue related to an specific MIPS extension?

R4000 ALLEGREX (A Sony PlayStation Portable extension)

### rabbitizer version

1.12.0

### Optional: splat/spimdisasm version

Yes, Splat 0.24.6

### Optional: Version of other stuff

Normal GNU AS does not support the PSP instructions. I am using the assembler installed from here: https://github.com/bismurphy/psp-binutils-installer/tree/main

Will follow up on whatever other tool versions might be relevant.

**Comment by bismurphy** [comment]
Hrrmmm. The instruction manual doesn't use brackets. So maybe it's the assembler that's wrong. Will follow up with them in parallel.

**Comment by bismurphy** [comment]
Closing this - it turns out the issue is in the assembler, which has the brackets as a workaround for a different issue. I have asked them to fix this, and it sounds like there is a path toward fixing. Not an issue with Rabbitizer then. Sorry to bother!

**Comment by AngheloAlf** [comment]
I want to note that this syntax was tested with an original SN toolchain, both with the SN assembler and the SN objdump, so ideally other assemblers would follow this same syntax.
Hopefully since you are using a binutils fork then updating it to accept the correct syntax shouldn't be a big issue.
